# syntax=docker/dockerfile:1
FROM jupyter/datascience-notebook

USER root
ENV  JUPYTER_TOKEN hi
WORKDIR .
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
RUN pip install psycopg2 ipython-sql \
EXPOSE 8888
COPY ./analytics ./analytics/
COPY ./db ./db/