# syntax=docker/dockerfile:1
FROM jupyter/datascience-notebook

USER root
WORKDIR .
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 \
    && pip install ipython-sql
EXPOSE 8888
COPY . .
