version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db:/db/
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: always

  datascience-notebook:
      container_name: datascience-notebook-container
      build:
        context: .
        dockerfile: Dockerfile-analytics
      volumes:
        - .:/analytics/project_files
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: changeme
        DB_NAME: movies

      ports:
        - 8888:8888
      networks:
        - postgres
      restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:


